### ISSUE TITLE
Error creating journal entry

### ISSUE THREAD

**Issue by Randomisation** [Daxiongmao87/legend-lore-foundry#2]
The generation works fine, but when clicking accept it fails to create the journal entry and throws up this error in the console

![image](https://github.com/Daxiongmao87/legend-lore-foundry/assets/77389343/cafd2ef0-262e-4851-b797-2203798b6bde)

If you need more information, just let me know. This module is awesome and has so much promise!

**Comment by Randomisation** [comment]
Okay, I have tried it a couple more times and despite it throwing up that error, it appears to be working! :)

**Comment by Daxiongmao87** [comment]
> Okay, I have tried it a couple more times and despite it throwing up that error, it appears to be working! :)


Thanks for reporting this, once I get around to updating this, one of my priorities is to try to implement better error handling.  I know some errors are mysterious right now, which is a problem I hope to alleviate later.
