### ISSUE TITLE
Missing module.zip in latest release

### ISSUE THREAD

**Issue by TheTural** [Daxiongmao87/legend-lore-foundry#5]
The `download` attribute in `module.json` points to `[releases/latest/download/module.zip](https://github.com/Daxiongmao87/legend-lore/releases/latest/download/module.zip)` but there wasn't a module.zip included in the latest Github release, so it 404's on attempting to install/update in Foundry.

**Comment by Daxiongmao87** [comment]
thank you i will fix this today

**Comment by Daxiongmao87** [comment]
hey @TheTural , I've made changes to the module.json, please let me know if it works for you.

**Comment by Daxiongmao87** [comment]
Closing.  Feel free to open this if your issue is still not resolved
