### ISSUE TITLE
Cannot generate content via OpenAI API

### ISSUE THREAD

**Issue by DeadSpace161** [Daxiongmao87/legend-lore-foundry#6]
Foundry VTT version: 12 Build 331
Legend Lore version: v0.4.0

Issue description:
When attempting to generate content while utilizing the Legend Lore module via OpenAI API key in Foundry VTT, I get the below errors.  I have tested the OpenAI API to ensure that the API key, access, and any quotas are not an issue and can confirm that API calls are successful.  I have attempted to use the module with all JSON mode models, and others, from 3.5-turbo to gpt-4 to no avail.  I have tried leaving the base url box blank, inputting api.openai.com, and others to no avail.  

I was initially thinking it was due to the v12 Foundry VTT, but I cannot explain how that would prevent the API calls from being successful.  Any help is much appreciated!  I am stoked to be able to use this module!!!  Thank you for your time!

**Errors:**
Error parsing JSON.
Failed to get a response from OpenAI.
Error in OpenAI API request.

![image](https://github.com/user-attachments/assets/4f49e463-cb58-490d-af8f-b1a51ed33b5f)

**Comment by DeadSpace161** [comment]
Speaking of Foundry versions, do you have any plans to update this module to support version 12 build 311?

**Comment by JustAnotherIdea** [comment]
Can't recreate the issue. Can you confirm your settings? They should look something like this 
![image](https://github.com/user-attachments/assets/7b8b84c3-dcf0-447a-97fd-9320f12021dc)

The base URL set is "api.openai.com" and the models are "gpt-4o gpt-4o-mini gpt-4o-turbo gpt-4 gpt-3.5-turbo" (without quotes). Looking at it now, I see the default for the models wasn't updated. If that's the issue, I can fix that real quick.

**Comment by DeadSpace161** [comment]
It worked!!!!  Amazing!  I am not sure if you changed something or what, but just know that I really appreciate the assist!  

![image](https://github.com/user-attachments/assets/4e3ed058-2523-4756-b3f4-21f9b1f3d868)

**Comment by DeadSpace161** [comment]
Thanks again!
